"""
edge_explorer.py

Knowledge Liberation Module 2: Generate the questions the study DID NOT ASK.

This is the play layer. The shadow is GENERATIVE here, not restrictive.
Given a scope boundary, we push outward and ask: what lives beyond the edge?
What would flip the finding's sign? What puzzle piece is this, really?

License: CC0
Ported from github.com/JinnZ2/Logic-Ferret/knowledge/edge_explorer.py
"""

from dataclasses import dataclass, field
from typing import List, Dict, Optional, Any
from enum import Enum


# ============================================================
# EDGE TYPES
# ============================================================

class EdgeType(Enum):
    """Ways to push on the boundary of a finding."""
    ONTOLOGICAL_RECLASSIFICATION = "ontological_reclassification"
    POPULATION_INVERSION = "population_inversion"
    TIME_EXTENSION = "time_extension"
    ENVIRONMENT_TRANSPLANT = "environment_transplant"
    MECHANISM_SUBSTITUTION = "mechanism_substitution"
    SIGN_INVERSION = "sign_inversion"
    SCALE_JUMP = "scale_jump"
    ADAPTATION_REFRAME = "adaptation_reframe"


# ============================================================
# GENERATED QUESTIONS
# ============================================================

@dataclass
class EdgeQuestion:
    """A question generated by pushing on a scope boundary."""
    edge_type: EdgeType
    question: str
    why_it_matters: str
    what_it_would_reveal: str
    how_to_test: Optional[str] = None

    def format(self) -> str:
        return (
            f"[{self.edge_type.value.upper()}]\n"
            f"  Question: {self.question}\n"
            f"  Matters because: {self.why_it_matters}\n"
            f"  Would reveal: {self.what_it_would_reveal}\n"
            f"  How to probe: {self.how_to_test or 'open to exploration'}\n"
        )


@dataclass
class EdgeExploration:
    """Full exploration of the edges of a study's scope."""
    original_claim: str
    scope_boundary_examined: str
    generated_questions: List[EdgeQuestion] = field(default_factory=list)
    recombinations: List[str] = field(default_factory=list)

    def add_question(self, q: EdgeQuestion) -> None:
        self.generated_questions.append(q)

    def summary(self) -> str:
        lines = [
            "=" * 70,
            "EDGE EXPLORATION",
            "=" * 70,
            f"Original claim: {self.original_claim}",
            f"Scope examined: {self.scope_boundary_examined}",
            "",
            f"Generated {len(self.generated_questions)} edge questions:",
            "",
        ]
        for i, q in enumerate(self.generated_questions, 1):
            lines.append(f"--- Edge {i} ---")
            lines.append(q.format())

        if self.recombinations:
            lines.append("RECOMBINATIONS (where this study's finding fits with others):")
            for r in self.recombinations:
                lines.append(f"  > {r}")
            lines.append("")

        lines.append("These questions are the SHADOW made generative.")
        lines.append("Each one is a puzzle piece waiting for its puzzle.")
        lines.append("=" * 70)

        return "\n".join(lines)


# ============================================================
# EDGE EXPLORER
# ============================================================

class EdgeExplorer:
    """
    Given a study's scope, generate the questions it cannot answer --
    as seeds for new inquiry, not as critiques.
    """

    def explore(self,
                claim: str,
                what_was_measured: str,
                population: str,
                environment: str,
                duration: str,
                uncontrolled_variables: List[str]) -> EdgeExploration:
        """Push on every edge of the scope. Generate questions."""
        exploration = EdgeExploration(
            original_claim=claim,
            scope_boundary_examined=(
                f"pop={population}, env={environment}, t={duration}"
            )
        )

        for pusher in (
            lambda: self._push_ontological(claim, what_was_measured),
            lambda: self._push_population(claim, population),
            lambda: self._push_time(claim, duration),
            lambda: self._push_environment(claim, environment),
            lambda: self._push_sign(claim, uncontrolled_variables),
            lambda: self._push_adaptation(claim, what_was_measured),
            lambda: self._push_scale(claim),
            lambda: self._push_mechanism(claim, what_was_measured),
        ):
            q = pusher()
            if q:
                exploration.add_question(q)

        return exploration

    # ----------------------------------------------------------
    # EDGE PUSHERS
    # ----------------------------------------------------------

    def _push_ontological(self, claim: str, measured: str) -> Optional[EdgeQuestion]:
        """What ELSE could the instrument have been measuring?"""
        return EdgeQuestion(
            edge_type=EdgeType.ONTOLOGICAL_RECLASSIFICATION,
            question=(
                f"The instrument measured '{measured}'. The paper labels this "
                f"as evidence for: '{claim}'. But instruments measure physics, "
                f"not categories. What OTHER ontological category could produce "
                f"the same measurement signal?"
            ),
            why_it_matters=(
                "The physical signal (e.g. cortisol, skin conductance, reaction time) "
                "is real and reproducible. The CATEGORY the paper assigns to it "
                "(impairment, deficit, pathology) is an interpretation. Same signal, "
                "different category = different downstream application."
            ),
            what_it_would_reveal=(
                "Whether the finding is about a single underlying state or about "
                "multiple states that happen to produce similar measurements."
            ),
            how_to_test=(
                "Run the same measurement on a population KNOWN to have the "
                "alternative category (e.g. experienced first responders, "
                "long-tenured operators). If the signal is the same, the "
                "category assignment is suspect."
            ),
        )

    def _push_population(self, claim: str, population: str) -> Optional[EdgeQuestion]:
        """What about the inverse population?"""
        pop_lower = population.lower()

        if "student" in pop_lower or "undergraduate" in pop_lower:
            contrast = (
                "working adults in high-threat occupations (truck drivers, "
                "salvage crews, first responders, long-line fishers)"
            )
        elif "clinical" in pop_lower or "patient" in pop_lower:
            contrast = (
                "people with the same biology who never entered clinical pathways"
            )
        elif "adversity" in pop_lower or "trauma" in pop_lower:
            contrast = (
                "people who experienced similar exposure but did NOT present "
                "for study or clinical care -- the invisible survivors"
            )
        else:
            contrast = f"a population selected by OPPOSITE criteria than: {population}"

        return EdgeQuestion(
            edge_type=EdgeType.POPULATION_INVERSION,
            question=(
                f"The study observed its finding in: {population}. "
                f"What happens if you measure the same thing in {contrast}?"
            ),
            why_it_matters=(
                "Selection shapes what you can see. The population IS the lens. "
                "The inverse population reveals whether the finding is about "
                "the variable studied -- or about the selection filter."
            ),
            what_it_would_reveal=(
                "Whether the effect is general, or whether it's an artifact "
                "of WHO could be recruited into the study in the first place."
            ),
            how_to_test=(
                "Replicate the measurement in a population that couldn't/wouldn't "
                "participate in the original. Field measurement rather than lab."
            ),
        )

    def _push_time(self, claim: str, duration: str) -> Optional[EdgeQuestion]:
        return EdgeQuestion(
            edge_type=EdgeType.TIME_EXTENSION,
            question=(
                f"The study measured over {duration}. "
                f"What does the same signal look like over months? Years? Decades? "
                f"Across a career? Across generations?"
            ),
            why_it_matters=(
                "Phenomena have characteristic time scales. A single-session "
                "measurement cannot see accumulation, fatigue, recalibration, "
                "adaptation, or transmission. The shape of the finding may "
                "invert at longer scales."
            ),
            what_it_would_reveal=(
                "Whether the observed state is stable, drifting, accumulating, "
                "or reversing -- and whether today's 'pathology' is tomorrow's "
                "adaptation (or vice versa)."
            ),
            how_to_test=(
                "Longitudinal followup. Or cross-sectional comparison across "
                "populations with different tenure in the relevant condition."
            ),
        )

    def _push_environment(self, claim: str, environment: str) -> Optional[EdgeQuestion]:
        if "lab" not in environment.lower():
            return None
        return EdgeQuestion(
            edge_type=EdgeType.ENVIRONMENT_TRANSPLANT,
            question=(
                f"The study was conducted in: {environment}. "
                f"Lab conditions SELECT for a narrow envelope of threat, noise, "
                f"and stake. What happens when you measure the same thing during "
                f"actual high-consequence work -- operating equipment, driving at "
                f"night, responding to an emergency?"
            ),
            why_it_matters=(
                "Lab threats are symbolic. Real threats have consequences. "
                "The nervous system may respond DIFFERENTLY to symbolic vs. real "
                "threat -- and the symbolic response may not predict the real one."
            ),
            what_it_would_reveal=(
                "Whether the measurement was tracking threat response or "
                "tracking response to the symbolic representation of threat -- "
                "which are potentially different circuits."
            ),
            how_to_test=(
                "Ambulatory measurement during actual high-stakes activity. "
                "Compare to lab response in the same individuals."
            ),
        )

    def _push_sign(self, claim: str, uncontrolled: List[str]) -> Optional[EdgeQuestion]:
        if not uncontrolled:
            return None
        return EdgeQuestion(
            edge_type=EdgeType.SIGN_INVERSION,
            question=(
                f"The uncontrolled variables include: {', '.join(uncontrolled[:3])}. "
                f"Under what values of these variables would the finding's SIGN "
                f"flip -- i.e. the observed 'deficit' become a functional strength, "
                f"or vice versa?"
            ),
            why_it_matters=(
                "A finding's sign is relative to its context. What looks like "
                "impairment in one environment may be precision in another. "
                "Finding the sign-inversion boundary locates the real claim."
            ),
            what_it_would_reveal=(
                "The actual domain of applicability -- which is where the "
                "study legitimately speaks, and where it must fall silent."
            ),
            how_to_test=(
                "Identify populations operating under the inverse values of "
                "uncontrolled variables. Compare outcomes."
            ),
        )

    def _push_adaptation(self, claim: str, measured: str) -> Optional[EdgeQuestion]:
        pathology_words = ["deficit", "impair", "dysregul", "blunted",
                           "reduced", "abnormal", "disorder"]
        if not any(w in claim.lower() for w in pathology_words):
            return None
        return EdgeQuestion(
            edge_type=EdgeType.ADAPTATION_REFRAME,
            question=(
                f"The claim uses pathology language: '{claim}'. "
                f"If the measured state is common in populations that SURVIVED "
                f"the conditions the original population experienced, is it "
                f"better described as adaptation than deficit?"
            ),
            why_it_matters=(
                "Pathology framing is load-bearing in clinical and policy decisions. "
                "Misframing an adaptation as a pathology leads to interventions "
                "that REMOVE the adaptation and REDUCE function. Information atrophy "
                "becomes active harm."
            ),
            what_it_would_reveal=(
                "Whether the measured state increases or decreases "
                "real-world survival and function in the environment where it evolved."
            ),
            how_to_test=(
                "Outcome measurement in the adaptive environment, not the lab. "
                "Ask: do people with this state outperform or underperform "
                "in their actual context?"
            ),
        )

    def _push_scale(self, claim: str) -> Optional[EdgeQuestion]:
        return EdgeQuestion(
            edge_type=EdgeType.SCALE_JUMP,
            question=(
                f"The claim is stated at the individual scale: '{claim}'. "
                f"How does this aggregate at the population, community, or "
                f"ecological scale? Does it reverse? Amplify? Distribute unevenly?"
            ),
            why_it_matters=(
                "Individual findings don't always aggregate linearly. A pattern "
                "that looks maladaptive in one person may be load-bearing for "
                "group function (threat-sensing in a team, risk distribution, "
                "redundancy). Removing the 'deficit' individually may damage "
                "the system."
            ),
            what_it_would_reveal=(
                "Whether the finding describes something about individuals or "
                "something about distributions within functional groups."
            ),
            how_to_test=(
                "Team/community-level outcome measurement with varying "
                "proportions of the measured trait."
            ),
        )

    def _push_mechanism(self, claim: str, measured: str) -> Optional[EdgeQuestion]:
        return EdgeQuestion(
            edge_type=EdgeType.MECHANISM_SUBSTITUTION,
            question=(
                f"The study correlates the measured signal ({measured}) with the "
                f"named cause. What other causal pathway could produce the same "
                f"signal? If the cause is replaced but the signal remains, the "
                f"original attribution is wrong."
            ),
            why_it_matters=(
                "Correlation at the measurement layer can be produced by multiple "
                "mechanisms. Naming one is a choice. The choice determines "
                "downstream intervention."
            ),
            what_it_would_reveal=(
                "Whether the intervention implied by the named mechanism would "
                "actually change the signal -- or whether another mechanism "
                "would regenerate it."
            ),
            how_to_test=(
                "Intervention studies targeting the named mechanism vs. "
                "alternative mechanisms. Signal response disambiguates."
            ),
        )


# ============================================================
# CONVENIENCE
# ============================================================

def explore_edges(claim: str,
                  what_was_measured: str,
                  population: str,
                  environment: str,
                  duration: str,
                  uncontrolled_variables: List[str]) -> str:
    """Quick edge exploration, returns formatted output."""
    explorer = EdgeExplorer()
    exploration = explorer.explore(
        claim=claim,
        what_was_measured=what_was_measured,
        population=population,
        environment=environment,
        duration=duration,
        uncontrolled_variables=uncontrolled_variables,
    )
    return exploration.summary()


# ============================================================
# EXAMPLE
# ============================================================

if __name__ == "__main__":
    result = explore_edges(
        claim="Childhood adversity associated with blunted threat response",
        what_was_measured="Skin conductance response to conditioned threat cues",
        population="Undergraduate students with self-reported ACE scores",
        environment="University lab",
        duration="Single session, ~45 minutes",
        uncontrolled_variables=[
            "Real-world threat exposure history",
            "Current environment threat level",
            "Pain tolerance baseline",
            "Prior learning/recalibration from survived events",
        ]
    )
    print(result)
